services:
  db:
    image: postgres:15
    container_name: postgres-db
    user: postgres
    restart: always
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=counter
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  service:
    build: .
    container_name: service
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=counter
      - POSTGRES_PORT=5432
    ports:
      - "50051:50051"
      - "3000:3000"

volumes:
  pg_data:

secrets:
  db-password:
    file: ./db/password.txt
